# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kuali < Formula
  desc "Connect Kuali to your AI assistant"
  homepage "https://github.com/kualico/kuali-connector"
  version "1.0.12-rc1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kualico/kuali-connector/releases/download/v1.0.12-rc1/kuali-darwin-amd64"
      sha256 "8edca2314c40d625e92fef292b72d3262bbcf9891fbdfee5a2b532dc7d1b176f"

      define_method(:install) do
        bin.install "kuali-darwin-amd64" => "kuali"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kualico/kuali-connector/releases/download/v1.0.12-rc1/kuali-darwin-arm64"
      sha256 "fa5979c07e95352c894f884c32641f631d7cfcf3ce20312377020b18d2c1a5f7"

      define_method(:install) do
        bin.install "kuali-darwin-arm64" => "kuali"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kualico/kuali-connector/releases/download/v1.0.12-rc1/kuali-linux-amd64"
      sha256 "52ac88c32b87fdb011d842910b0de39d0334cac76ebc26567c6bb431f4c298f0"
      define_method(:install) do
        bin.install "kuali-linux-amd64" => "kuali"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kualico/kuali-connector/releases/download/v1.0.12-rc1/kuali-linux-arm64"
      sha256 "61daeba5a7788f278746b626d28b98a1e1a7734218df852d70ceae7b8d1c99fc"
      define_method(:install) do
        bin.install "kuali-linux-arm64" => "kuali"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kuali version")
  end
end
