# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kuali < Formula
  desc "Connect Kuali to your AI assistant"
  homepage "https://github.com/kualico/kuali-connector"
  version "1.0.0-rc3"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kualico/kuali-connector/releases/download/v1.0.0-rc3/kuali-darwin-amd64"
      sha256 "19b8339324c73adfeacfe78f6a475c4212370bc0f63d507b52cfb6dd05ed3e18"

      define_method(:install) do
        bin.install "kuali-darwin-amd64" => "kuali"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kualico/kuali-connector/releases/download/v1.0.0-rc3/kuali-darwin-arm64"
      sha256 "21ba52c9c48d75d48cb98a6bd61b0196b2bd3aedc55436e77128f860156100d9"

      define_method(:install) do
        bin.install "kuali-darwin-arm64" => "kuali"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kualico/kuali-connector/releases/download/v1.0.0-rc3/kuali-linux-amd64"
      sha256 "9962fe50bedcae9783d7a2f06728ff38728b83cbd9be14f73f8693e41c471031"
      define_method(:install) do
        bin.install "kuali-linux-amd64" => "kuali"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kualico/kuali-connector/releases/download/v1.0.0-rc3/kuali-linux-arm64"
      sha256 "c21ad0e09f0b75816aca13a4e48c25b63b7979890e8fb5a1e2508ab2567410a9"
      define_method(:install) do
        bin.install "kuali-linux-arm64" => "kuali"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kuali version")
  end
end
